import type { TemplateType } from './types'

export interface FEFCOEntry {
  code: string
  name: string
  description: string
  series: string
  template: TemplateType
  defaultParams?: { width?: number; height?: number; depth?: number }
  isStandard: boolean
}

export const FEFCO_CATALOG: FEFCOEntry[] = [
  // ── 02xx — Boîtes découpées (Slotted) ─────────────────────────────────────
  { code: '0201', name: 'RSC',           series: '02 Découpés', template: 'fefco-rsc', isStandard: true,
    description: 'Regular Slotted Container — 4 paires de rabats égaux rejoignant le centre. Le plus répandu au monde.',
    defaultParams: { width: 200, height: 150, depth: 150 } },
  { code: '0202', name: 'HSC',           series: '02 Découpés', template: 'hsc-box', isStandard: true,
    description: 'Half Slotted Container — dessus ouvert, 4 rabats uniquement en bas. Idéal pour présentoirs PDV et plateaux de service.',
    defaultParams: { width: 300, height: 200, depth: 200 } },
  { code: '0203', name: 'CSSC',          series: '02 Découpés', template: 'osc-box', isStandard: true,
    description: 'Center Special Slotted — rabats extérieurs légèrement chevauchants, pour produits cylindriques ou ronds.',
    defaultParams: { width: 180, height: 130, depth: 180 } },
  { code: '0204', name: 'OSC',           series: '02 Découpés', template: 'osc-box', isStandard: true,
    description: 'Overlap Slotted Container — rabats qui se chevauchent de 25 mm minimum pour résistance accrue.',
    defaultParams: { width: 250, height: 200, depth: 180 } },
  { code: '0205', name: 'FOL',           series: '02 Découpés', template: 'fol-box', isStandard: true,
    description: 'Full Overlap Slotted — rabats extérieurs pleine profondeur D, double épaisseur sur dessus et dessous.',
    defaultParams: { width: 300, height: 250, depth: 200 } },
  { code: '0206', name: 'RSC Doublé',   series: '02 Découpés', template: 'box',     isStandard: false,
    description: 'RSC avec double paroi — renforcement latéral pour charges lourdes.',
    defaultParams: { width: 400, height: 300, depth: 300 } },
  { code: '0207', name: 'CSC Égal',     series: '02 Découpés', template: 'box',     isStandard: false,
    description: 'CSC variante — les 4 rabats ont la même profondeur, indépendamment des faces.',
    defaultParams: { width: 200, height: 150, depth: 200 } },
  { code: '0210', name: 'Mailer Box',   series: '02 Découpés', template: 'mailer',  isStandard: true,
    description: 'Boîte mailer auto-montante avec auto-verrouillage — idéale e-commerce.',
    defaultParams: { width: 300, height: 100, depth: 200 } },
  { code: '0211', name: 'Postal Box',   series: '02 Découpés', template: 'mailer',  isStandard: true,
    description: 'Boîte postale avec couvercle à verrouillage — envoi sans colle ni ruban.',
    defaultParams: { width: 280, height: 80, depth: 180 } },
  { code: '0212', name: 'Multi-Adhésif',series: '02 Découpés', template: 'mailer',  isStandard: false,
    description: 'Mailer multi-points adhésifs — refermeture possible pour retour client.',
    defaultParams: { width: 300, height: 60, depth: 200 } },
  { code: '0214', name: 'RSC Scellé',   series: '02 Découpés', template: 'box',     isStandard: false,
    description: 'RSC avec dessus scellé à la colle — inviolabilité garantie.',
    defaultParams: { width: 250, height: 200, depth: 180 } },
  { code: '0215', name: 'Self-Lock',    series: '02 Découpés', template: 'mailer',  isStandard: true,
    description: 'Mailer auto-verrouillable sans colle — languette de blocage intégrée.',
    defaultParams: { width: 280, height: 80, depth: 180 } },
  { code: '0216', name: 'OSC Égal',     series: '02 Découpés', template: 'osc-box', isStandard: false,
    description: 'OSC à 4 rabats identiques — tous se chevauchent uniformément.',
    defaultParams: { width: 240, height: 180, depth: 180 } },
  { code: '0217', name: 'Cross-Lock',   series: '02 Découpés', template: 'box',     isStandard: false,
    description: 'RSC avec fond à verrou croisé — résistance supérieure sans colle.',
    defaultParams: { width: 200, height: 150, depth: 150 } },

  // ── 03xx — Boîtes Bliss ────────────────────────────────────────────────────
  { code: '0300', name: 'Bliss 3 Pièces', series: '03 Bliss', template: 'snap-lock', isStandard: true,
    description: 'Boîte 3 pièces — corps tubulaire + 2 fonds indépendants, très résistante à l\'empilage.',
    defaultParams: { width: 200, height: 150, depth: 150 } },
  { code: '0301', name: 'Bliss Box',    series: '03 Bliss', template: 'snap-lock', isStandard: true,
    description: 'Boîte Bliss standard — 3 pièces assemblées, excellente résistance à la compression.',
    defaultParams: { width: 200, height: 150, depth: 150 } },
  { code: '0302', name: 'Plateau FEFCO', series: '03 Bliss', template: 'fefco-tray', isStandard: true,
    description: 'Plateau croix — fond central + 4 parois relevables + 4 contre-angles. Un seul pli de carton.',
    defaultParams: { width: 200, height: 60, depth: 300 } },
  { code: '0303', name: 'Bliss Intégré',series: '03 Bliss', template: 'snap-lock', isStandard: false,
    description: 'Bliss avec fond intégré — assemblage simplifié, 2 pièces au lieu de 3.',
    defaultParams: { width: 220, height: 160, depth: 160 } },
  { code: '0310', name: 'Bliss Renforcé',series: '03 Bliss', template: 'snap-lock', isStandard: false,
    description: 'Bliss avec cornières renforcées — très lourdes charges industrielles.',
    defaultParams: { width: 300, height: 200, depth: 250 } },
  { code: '0320', name: 'Télescopique', series: '03 Bliss', template: 'lid-box',   isStandard: true,
    description: 'Boîte télescopique pleine — fond + couvercle plein recouvrement, rigidité maximale.',
    defaultParams: { width: 200, height: 80, depth: 150 } },
  { code: '0330', name: 'Télescope Partiel', series: '03 Bliss', template: 'lid-box', isStandard: true,
    description: 'Télescopique partiel — couvercle recouvre 50% du corps, ouverture facile.',
    defaultParams: { width: 200, height: 60, depth: 150 } },
  { code: '0350', name: 'Bliss Double', series: '03 Bliss', template: 'snap-lock', isStandard: false,
    description: 'Bliss double paroi — résistance extrême pour transport longue distance.',
    defaultParams: { width: 300, height: 200, depth: 250 } },

  // ── 04xx — Boîtes folder (pliées) ─────────────────────────────────────────
  { code: '0401', name: 'Folder Simple', series: '04 Folder', template: 'lid-box',  isStandard: true,
    description: 'Boîte plate 4 rabats — intercalaires pour produits plats, cahiers, électronique.',
    defaultParams: { width: 300, height: 30, depth: 200 } },
  { code: '0402', name: 'Folder 2 Pièces', series: '04 Folder', template: 'lid-box', isStandard: true,
    description: 'Fond + couvercle séparés avec emboîtement — boîte cadeau rigide haut de gamme.',
    defaultParams: { width: 200, height: 60, depth: 150 } },
  { code: '0403', name: 'Folder 3 Panneaux', series: '04 Folder', template: 'lid-box', isStandard: false,
    description: 'Folder 3 panneaux avec ailettes — emballage primaire textile.',
    defaultParams: { width: 250, height: 40, depth: 180 } },
  { code: '0404', name: 'Wrap-Around',  series: '04 Folder', template: 'tray-box', isStandard: true,
    description: 'Caisse enveloppante — se forme autour du produit, zéro volume vide.',
    defaultParams: { width: 300, height: 100, depth: 200 } },
  { code: '0405', name: 'Seal-End Wrap',series: '04 Folder', template: 'seal-end', isStandard: true,
    description: 'Folder scellé haut et bas — emballage pharma et cosmétique.',
    defaultParams: { width: 60, height: 180, depth: 40 } },
  { code: '0406', name: 'Folder Verrouillé', series: '04 Folder', template: 'tuck-end', isStandard: false,
    description: 'Folder avec verrouillage intérieur — résiste à l\'ouverture accidentelle.',
    defaultParams: { width: 80, height: 200, depth: 60 } },
  { code: '0409', name: 'Folder Poignée', series: '04 Folder', template: 'gable',  isStandard: false,
    description: 'Folder avec poignée intégrée — porteur alimentaire ou retail.',
    defaultParams: { width: 100, height: 250, depth: 100 } },
  { code: '0410', name: 'Folder 2P Couvercle', series: '04 Folder', template: 'lid-box', isStandard: true,
    description: 'Fond + couvercle séparés — boîte cadeau rigide classique.',
    defaultParams: { width: 200, height: 60, depth: 150 } },
  { code: '0420', name: 'Folder Collé', series: '04 Folder', template: 'tuck-end', isStandard: false,
    description: 'Folder avec joint de colle sur le haut — fermeture hermétique alimentaire.',
    defaultParams: { width: 80, height: 200, depth: 60 } },
  { code: '0421', name: 'Tuck-End',     series: '04 Folder', template: 'fefco-0713', isStandard: true,
    description: 'Boîte à glissière — corps D|W|D|W, volets dépoussiéreurs + couvercle+languette. Standard pharma et cosmétique.',
    defaultParams: { width: 80, height: 200, depth: 60 } },
  { code: '0426', name: 'Snap-Tuck',    series: '04 Folder', template: 'tuck-end', isStandard: true,
    description: 'Tuck-end avec verrouillage snap — sécurité anti-ouverture renforcée.',
    defaultParams: { width: 70, height: 180, depth: 50 } },
  { code: '0427', name: 'Auto-Bottom',  series: '04 Folder', template: 'auto-bottom', isStandard: true,
    description: 'Fond automatique à la pose — cadence rapide en ligne de production.',
    defaultParams: { width: 100, height: 200, depth: 80 } },
  { code: '0428', name: 'Crash-Lock',   series: '04 Folder', template: 'crash-lock-bottom', isStandard: true,
    description: 'Verrou automatique fond — résistance supérieure au RSC, idéal e-commerce.',
    defaultParams: { width: 120, height: 200, depth: 100 } },
  { code: '0430', name: 'Roll-End Lock',series: '04 Folder', template: 'auto-bottom', isStandard: true,
    description: 'Fond roll-end à verrou — montage manuel rapide, résistance élevée.',
    defaultParams: { width: 110, height: 200, depth: 90 } },
  { code: '0435', name: 'Tuck + Dust',  series: '04 Folder', template: 'tuck-end', isStandard: true,
    description: 'Tuck-end avec volets latéraux — protection totale du produit, haute qualité perçue.',
    defaultParams: { width: 90, height: 220, depth: 70 } },

  // ── 05xx — Plateaux ────────────────────────────────────────────────────────
  { code: '0501', name: 'Plateau Simple', series: '05 Plateau', template: 'fefco-tray', isStandard: true,
    description: 'Plateau croix une pièce — fond + 4 parois + contre-angles, idéal pour présentoir PDV.',
    defaultParams: { width: 200, height: 80, depth: 300 } },
  { code: '0502', name: 'Plateau + Couvercle', series: '05 Plateau', template: 'tray-box', isStandard: true,
    description: 'Plateau fond + couvercle emboîté — coffret cadeau accessible.',
    defaultParams: { width: 250, height: 60, depth: 180 } },
  { code: '0503', name: 'Plateau Tuck',  series: '05 Plateau', template: 'tray-box', isStandard: true,
    description: 'Plateau avec languettes tuck aux extrémités — fermeture sans colle.',
    defaultParams: { width: 280, height: 70, depth: 190 } },
  { code: '0504', name: 'Plateau Collé', series: '05 Plateau', template: 'tray-box', isStandard: false,
    description: 'Plateau entièrement collé — résistance maximale pour charges lourdes.',
    defaultParams: { width: 350, height: 100, depth: 250 } },
  { code: '0505', name: 'Plateau Snap',  series: '05 Plateau', template: 'snap-lock', isStandard: true,
    description: 'Plateau à snap-lock — montage instantané sans colle ni outillage.',
    defaultParams: { width: 200, height: 60, depth: 150 } },
  { code: '0508', name: 'Snap-Lock Tray',series: '05 Plateau', template: 'snap-lock', isStandard: true,
    description: 'Plateau à snap-lock — montage sans colle.',
    defaultParams: { width: 200, height: 60, depth: 150 } },
  { code: '0510', name: 'Présentoir Tray',series: '05 Plateau', template: 'display', isStandard: true,
    description: 'Plateau demi-hauteur pour présentoir palette — visibilité produit maximale.',
    defaultParams: { width: 400, height: 200, depth: 300 } },

  // ── 06xx — Boîtes spéciales ────────────────────────────────────────────────
  { code: '0601', name: 'Crash-Lock Pro',series: '06 Spéciaux', template: 'crash-lock-bottom', isStandard: true,
    description: 'Crash-lock fond renforcé — boîtes carton lourd, résistance supérieure.',
    defaultParams: { width: 150, height: 250, depth: 120 } },
  { code: '0602', name: 'Seal-End',     series: '06 Spéciaux', template: 'seal-end', isStandard: true,
    description: 'Boîte cosmétique/pharma à rabats scellés haut et bas.',
    defaultParams: { width: 60, height: 180, depth: 40 } },
  { code: '0605', name: 'Reverse Tuck', series: '06 Spéciaux', template: 'reverse-tuck', isStandard: true,
    description: 'Tuck inversé — blister pharma, languettes haut/bas opposées.',
    defaultParams: { width: 50, height: 120, depth: 30 } },
  { code: '0609', name: 'Tuck-Top',     series: '06 Spéciaux', template: 'tuck-end', isStandard: true,
    description: 'Tuck-top avec fond auto — emballage cosmétique premium.',
    defaultParams: { width: 70, height: 200, depth: 50 } },
  { code: '0610', name: '1-Pièce Folder',series: '06 Spéciaux', template: 'box',    isStandard: false,
    description: 'Folder mono-pièce avec rabats intégrés — emballage rapide food-service.',
    defaultParams: { width: 250, height: 80, depth: 200 } },
  { code: '0616', name: 'Window Box',   series: '06 Spéciaux', template: 'window-box', isStandard: true,
    description: 'Boîte avec fenêtre — visibilité produit, confiserie et cosmétique.',
    defaultParams: { width: 100, height: 200, depth: 60 } },
  { code: '0620', name: 'Multi-Panneau',series: '06 Spéciaux', template: 'box',     isStandard: false,
    description: 'Boîte multi-panneaux spéciaux — formes complexes sur mesure.',
    defaultParams: { width: 150, height: 200, depth: 120 } },
  { code: '0623', name: 'Pillow Box',   series: '06 Spéciaux', template: 'pillow-box', isStandard: true,
    description: 'Boîte coussin arrondie — bijoux et cadeaux premium.',
    defaultParams: { width: 150, height: 80, depth: 60 } },
  { code: '0631', name: 'Hexagonal',    series: '06 Spéciaux', template: 'hexagonal-box', isStandard: false,
    description: 'Prisme hexagonal 6 faces — confiserie luxe et cosmétique.',
    defaultParams: { width: 120, height: 100, depth: 120 } },

  // ── 07xx — Porteurs et spéciaux ────────────────────────────────────────────
  { code: '0701', name: 'Porteur Basic',series: '07 Porteurs', template: 'gable',   isStandard: true,
    description: 'Porteur basique avec poignée — transport alimentaire ou retail.',
    defaultParams: { width: 100, height: 250, depth: 100 } },
  { code: '0711', name: 'Gable Top',    series: '07 Porteurs', template: 'gable',   isStandard: true,
    description: 'Carton gable milk-carton — alimentaire liquide et UHT.',
    defaultParams: { width: 100, height: 250, depth: 100 } },
  { code: '0712', name: 'Flip-Top',     series: '07 Porteurs', template: 'flip-top',isStandard: true,
    description: 'Boîte à couvercle articulé — cosmétique et parfumerie haut de gamme.',
    defaultParams: { width: 80, height: 200, depth: 60 } },
  { code: '0713', name: 'Drawer Box',   series: '07 Porteurs', template: 'drawer-box', isStandard: true,
    description: 'Boîte tiroir avec manchon — coffret cadeau luxe, montres et bijoux.',
    defaultParams: { width: 150, height: 80, depth: 200 } },
  { code: '0714', name: 'Beer Carrier', series: '07 Porteurs', template: 'gable',   isStandard: true,
    description: 'Porteur 6 bouteilles bière/vin — renforcé pour charges liquides.',
    defaultParams: { width: 240, height: 280, depth: 160 } },
  { code: '0715', name: 'Bottle Carrier 4',series: '07 Porteurs', template: 'gable',isStandard: true,
    description: 'Porteur 4 bouteilles avec séparations intégrées.',
    defaultParams: { width: 180, height: 260, depth: 120 } },
  { code: '0716', name: 'Bottle Carrier 6',series: '07 Porteurs', template: 'gable',isStandard: true,
    description: 'Porteur 6 bouteilles avec alvéoles — grande surface de branding.',
    defaultParams: { width: 260, height: 280, depth: 130 } },
  { code: '0730', name: 'Ballotin',     series: '07 Porteurs', template: 'ballotin',isStandard: false,
    description: 'Ballotin chocolaterie avec couvercle rabattu — luxe confiserie.',
    defaultParams: { width: 150, height: 80, depth: 100 } },

  // ── 09xx — Displays (PDV / PLV) ───────────────────────────────────────────
  { code: '0901', name: 'SRP Display',  series: '09 Displays', template: 'display', isStandard: true,
    description: 'Shelf-Ready Packaging — caisse de transport qui devient présentoir en rayon.',
    defaultParams: { width: 400, height: 200, depth: 300 } },
  { code: '0902', name: 'Counter Display',series: '09 Displays', template: 'display',isStandard: true,
    description: 'Présentoir comptoir — PLV de petit format pour caisses et comptoirs.',
    defaultParams: { width: 200, height: 300, depth: 150 } },
  { code: '0910', name: 'Floor Display',series: '09 Displays', template: 'display', isStandard: true,
    description: 'Présentoir sol avec perforations d\'ouverture — déploiement rapide en magasin.',
    defaultParams: { width: 400, height: 600, depth: 300 } },

  // ── Flexibles (hors FEFCO officiel) ───────────────────────────────────────
  { code: 'E-001', name: 'Enveloppe',   series: 'Flexibles', template: 'envelope',    isStandard: false,
    description: 'Enveloppe standard — panneau avant + volet scellant triangulaire + volets latéraux + fond collé.',
    defaultParams: { width: 229, height: 162, depth: 20 } },
  { code: 'E-002', name: 'Plateau Plat',series: 'Flexibles', template: 'shallow-box', isStandard: false,
    description: 'Plateau croix à coins ouverts — fond plat + 4 parois sans contre-angles, montage direct sans colle.',
    defaultParams: { width: 200, height: 30, depth: 300 } },
  { code: 'F-101', name: 'Sleeve Étui',  series: 'Flexibles', template: 'sleeve-insert', isStandard: false,
    description: 'Étui manchon + plateau intérieur — électronique et cosmétique.',
    defaultParams: { width: 200, height: 80, depth: 150 } },
  { code: 'F-201', name: 'Stand-Up Pouch',series: 'Flexibles', template: 'stand-up-pouch', isStandard: false,
    description: 'Sachet debout doy-pack — alimentaire, café, snacks.',
    defaultParams: { width: 150, height: 250, depth: 80 } },
  { code: 'F-301', name: 'Flow Wrap',   series: 'Flexibles', template: 'flow-wrap', isStandard: false,
    description: 'Film étirable horizontal — boulangerie, biscuits, confiserie.',
    defaultParams: { width: 200, height: 60, depth: 100 } },
  { code: 'F-401', name: 'Blister Pack',series: 'Flexibles', template: 'blister-pack', isStandard: false,
    description: 'Blister thermoformé — pharma, vis, électronique.',
    defaultParams: { width: 120, height: 200, depth: 30 } },
]

export const FEFCO_SERIES = FEFCO_CATALOG.map(e => e.series).filter((s, i, arr) => arr.indexOf(s) === i)

export function getFEFCOEntry(code: string): FEFCOEntry | undefined {
  return FEFCO_CATALOG.find(e => e.code === code)
}

export function getFEFCOByTemplate(template: TemplateType): FEFCOEntry[] {
  return FEFCO_CATALOG.filter(e => e.template === template)
}
