import type { TemplateType } from './types'

export interface PacklyArticle {
  code: string
  model: string
  variant: string
  title: string
  slug: string
  categories: string[]
  defaultA: number
  defaultB: number
  defaultH: number
  panelCount: number
  alphaCount: number
  materials: string[]
  corrugated: boolean
  mockup: string
  template: TemplateType
}

export const PACKLY_CATEGORY_NAMES: Record<string, string> = {
  RF: 'Straight line',
  TL: 'Trays & lids',
  SF: 'Specialty boxes',
  AB: 'Auto bottom',
  AC: 'Accessories',
  DB: 'Displays',
  '123B': '1-2-3 bottom',
}

export const PACKLY_CATALOG: PacklyArticle[] = [
  { code: 's001_v0', model: 's001', variant: 'v0', title: "Reverse tuck end box", slug: 'tuck-end-box-reverse-tuck-end', categories: ["RF"], defaultA: 80, defaultB: 80, defaultH: 150, panelCount: 13, alphaCount: 9, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/tuck_end_box_reverse_tuck_end_b48745d098.svg", template: 'reverse-tuck' },
  { code: 's001_v1', model: 's001', variant: 'v1', title: "Tuck end box with aero tuck to back", slug: 'tuck-end-box-aerotuck-to-back', categories: ["RF"], defaultA: 80, defaultB: 80, defaultH: 150, panelCount: 13, alphaCount: 9, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/tuck_end_box_aero_tuck_to_back_40b023d1da.svg", template: 'tuck-end' },
  { code: 's001_v2', model: 's001', variant: 'v2', title: "Same panel tuck end box", slug: 'tuck-end-box-same-panel-tuck', categories: ["RF"], defaultA: 80, defaultB: 80, defaultH: 150, panelCount: 13, alphaCount: 9, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/tuck_end_box_same_panel_tuck_1_cdb8147b1a.svg", template: 'tuck-end' },
  { code: 's001_v3', model: 's001', variant: 'v3', title: "Reverse tuck end slim box", slug: 'tuck-end-slim-box-reverse-tuck-end', categories: ["RF"], defaultA: 90, defaultB: 10, defaultH: 150, panelCount: 13, alphaCount: 9, materials: ["cardboard", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/tuck_end_slim_box_reverse_tuck_end_0b3d13bf46.svg", template: 'reverse-tuck' },
  { code: 's001_v4', model: 's001', variant: 'v4', title: "Tuck end slim box with aero tuck to back", slug: 'tuck-end-slim-box-aerotuck-to-back', categories: ["RF"], defaultA: 90, defaultB: 10, defaultH: 150, panelCount: 13, alphaCount: 9, materials: ["cardboard", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/tuck_end_slim_box_aero_tuck_to_back_2bd7f03b50.svg", template: 'tuck-end' },
  { code: 's001_v5', model: 's001', variant: 'v5', title: "Same panel tuck end slim box", slug: 'tuck-end-slim-box-same-panel-tuck', categories: ["RF"], defaultA: 90, defaultB: 10, defaultH: 150, panelCount: 13, alphaCount: 9, materials: ["cardboard", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/tuck_end_slim_box_same_panel_tuck_70e9766192.svg", template: 'tuck-end' },
  { code: 's002_v0', model: 's002', variant: 'v0', title: "Standard rollover hinged lid box", slug: 'rollover-hinged-lid-box-standard', categories: ["TL"], defaultA: 150, defaultB: 100, defaultH: 40, panelCount: 15, alphaCount: 11, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/rollover_hinged_lid_box_standard_786e2b18d4.svg", template: 'lid-box' },
  { code: 's002_v1', model: 's002', variant: 'v1', title: "Rollover hinged lid box with buttonhole", slug: 'rollover-hinged-lid-box-buttonhole', categories: ["TL"], defaultA: 150, defaultB: 100, defaultH: 40, panelCount: 15, alphaCount: 11, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/rollover_hinged_lid_buttonhole_af9c5c0e16.svg", template: 'lid-box' },
  { code: 's002_v2', model: 's002', variant: 'v2', title: "Rollover hinged lid box with hook lock", slug: 'rollover-hinged-lid-box-hook', categories: ["TL"], defaultA: 150, defaultB: 100, defaultH: 40, panelCount: 16, alphaCount: 13, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/rollover_hinged_lid_hook_c1d974776c.svg", template: 'lid-box' },
  { code: 's002_v3', model: 's002', variant: 'v3', title: "Rollover hinged lid with 3 inside flaps", slug: 'rollover-hinged-lid-with-3-inside-flaps', categories: [], defaultA: 165, defaultB: 165, defaultH: 40, panelCount: 13, alphaCount: 10, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/rollover_hinged_lid_with_3_inside_flaps_cb44ed1fdd.svg", template: 'lid-box' },
  { code: 's002_v4', model: 's002', variant: 'v4', title: "Standard rollover hinged lid box with inside printing", slug: 'rollover-hinged-lid-box-with-inside-printing', categories: ["TL"], defaultA: 150, defaultB: 100, defaultH: 40, panelCount: 15, alphaCount: 11, materials: ["cardboard", "corrugated", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/rollover_hinged_lid_standard_inside_printing_0b48316435.svg", template: 'lid-box' },
  { code: 's003_v0', model: 's003', variant: 'v0', title: "Lid and bottom box with 3/4 height lid", slug: 'lid-and-bottom-box-3q', categories: ["TL"], defaultA: 150, defaultB: 100, defaultH: 35, panelCount: 30, alphaCount: 16, materials: ["cardboard", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/lid_and_bottom_box_3_4_height_lid_63f836d7b0.svg", template: 'lid-box' },
  { code: 's003_v1', model: 's003', variant: 'v1', title: "Lid and bottom box with full height lid", slug: 'lid-and-bottom-box-full-height', categories: ["TL"], defaultA: 150, defaultB: 100, defaultH: 35, panelCount: 30, alphaCount: 16, materials: ["cardboard", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/lid_and_bottom_box_full_height_lid_7c7945a6e4.svg", template: 'lid-box' },
  { code: 's003_v2', model: 's003', variant: 'v2', title: "Lid and bottom box with double wall and 3/4 height lid", slug: 'lid-bottom-box-double-wall-3q', categories: ["TL"], defaultA: 150, defaultB: 80, defaultH: 35, panelCount: 32, alphaCount: 14, materials: ["cardboard", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/lid_and_bottom_box_double_wall_and_3_4_height_lid_ccc4c9add0.svg", template: 'lid-box' },
  { code: 's003_v3', model: 's003', variant: 'v3', title: "Lid and bottom box with double wall and full height lid", slug: 'lid-bottom-box-double-wall-full-height', categories: ["TL"], defaultA: 150, defaultB: 80, defaultH: 35, panelCount: 32, alphaCount: 14, materials: ["cardboard", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/lid_and_bottom_box_double_wall_and_full_heigth_lid_b750b4e087.svg", template: 'lid-box' },
  { code: 's004_v0', model: 's004', variant: 'v0', title: "1-2-3 bottom box with tuck to back", slug: '1-2-3-bottom-box-tuck-to-back', categories: ["123B", "RF"], defaultA: 150, defaultB: 80, defaultH: 100, panelCount: 13, alphaCount: 9, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/1_2_3_bottom_box_tuck_to_back_385adf5751.svg", template: 'crash-lock-bottom' },
  { code: 's004_v1', model: 's004', variant: 'v1', title: "1-2-3 bottom box with tuck to front", slug: '1-2-3-bottom-box-tuck-to-front', categories: ["123B", "RF"], defaultA: 150, defaultB: 80, defaultH: 100, panelCount: 13, alphaCount: 9, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/1_2_3_bottom_box_tuck_to_front_b397569402.svg", template: 'crash-lock-bottom' },
  { code: 's005_v0', model: 's005', variant: 'v0', title: "Two flaps folder with spine", slug: 'two-flaps-folder-with-spiner', categories: [], defaultA: 210, defaultB: 10, defaultH: 297, panelCount: 7, alphaCount: 3, materials: ["cardboard", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/folder_with_spine_2_flaps_cd2b33ce3d.svg", template: 'fourreau-auto' },
  { code: 's005_v1', model: 's005', variant: 'v1', title: "Three flaps folder with spine", slug: 'three-flaps-folder-with-spine', categories: ["AC"], defaultA: 210, defaultB: 297, defaultH: 10, panelCount: 9, alphaCount: 3, materials: ["cardboard"], corrugated: false, mockup: "", template: 'fourreau-semi-auto' },
  { code: 's006_v0', model: 's006', variant: 'v0', title: "Auto bottom box with tuck to back", slug: 'auto-bottom-box-tuck-to-back', categories: ["AB", "RF"], defaultA: 130, defaultB: 80, defaultH: 100, panelCount: 15, alphaCount: 11, materials: ["cardboard", "corrugated", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/auto_bottom_box_tuck_to_back_2851698fe6.svg", template: 'auto-bottom' },
  { code: 's006_v1', model: 's006', variant: 'v1', title: "Auto bottom box with tuck to front", slug: 'auto-bottom-box-tuck-to-front', categories: ["AB", "RF"], defaultA: 130, defaultB: 80, defaultH: 100, panelCount: 15, alphaCount: 11, materials: ["cardboard", "corrugated", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/auto_bottom_box_tuck_to_front_eac98d1fd8.svg", template: 'auto-bottom' },
  { code: 's007_v0', model: 's007', variant: 'v0', title: "Tuck end hanging box", slug: 'hanging-box-tuck-end', categories: ["DB", "SF"], defaultA: 60, defaultB: 20, defaultH: 100, panelCount: 15, alphaCount: 11, materials: ["cardboard", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/hanging_box_tuck_end_5197e860c1.svg", template: 'hanging-box' },
  { code: 's007_v1', model: 's007', variant: 'v1', title: "1-2-3 bottom hanging box", slug: 'hanging-box-1-2-3-bottom', categories: ["123B", "DB", "SF"], defaultA: 60, defaultB: 20, defaultH: 100, panelCount: 15, alphaCount: 11, materials: ["cardboard", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/hanging_box_1_2_3_bottom_59d25f3651.svg", template: 'hanging-box' },
  { code: 's007_v2', model: 's007', variant: 'v2', title: "Auto bottom hanging box", slug: 'hanging-box-crash-lock-bottom', categories: ["AB", "DB", "SF"], defaultA: 80, defaultB: 30, defaultH: 100, panelCount: 17, alphaCount: 13, materials: ["cardboard", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/hanging_box_crash_lock_bottom_e5de2d5213.svg", template: 'hanging-box' },
  { code: 's007_v3', model: 's007', variant: 'v3', title: "Tuck end slim box with front hang hole", slug: 'slim-front-hanging-box-tuck-end', categories: ["DB", "SF"], defaultA: 100, defaultB: 10, defaultH: 120, panelCount: 15, alphaCount: 11, materials: ["cardboard", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/slim_hanging_box_front_hang_hole_tuck_end_7634f6a214.svg", template: 'hanging-box' },
  { code: 's007_v4', model: 's007', variant: 'v4', title: "Tuck end slim box with back hang hole", slug: 'slim-back-hanging-box-tuck-end', categories: ["SF"], defaultA: 100, defaultB: 10, defaultH: 120, panelCount: 15, alphaCount: 11, materials: ["cardboard", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/slim_hanging_box_back_hang_hole_tuck_end_6267e1ced1.svg", template: 'hanging-box' },
  { code: 's008_v0', model: 's008', variant: 'v0', title: "Pull out box with standard tray", slug: 'pull-out-box-standard-tray', categories: ["TL"], defaultA: 150, defaultB: 90, defaultH: 30, panelCount: 20, alphaCount: 9, materials: ["cardboard", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/pull_out_box_standard_tray_596f420ed8.svg", template: 'drawer-box' },
  { code: 's008_v1', model: 's008', variant: 'v1', title: "Pull out box with double wall tray", slug: 'pull-out-box-double-wall-tray', categories: ["TL"], defaultA: 140, defaultB: 85, defaultH: 30, panelCount: 22, alphaCount: 7, materials: ["cardboard", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/pull_out_box_double_wall_tray_d7702b8e90.svg", template: 'drawer-box' },
  { code: 's009_v0', model: 's009', variant: 'v0', title: "Auto bottom box with lid", slug: 'auto-bottom-box-with-lid', categories: ["RF", "AB", "TL"], defaultA: 130, defaultB: 60, defaultH: 100, panelCount: 26, alphaCount: 17, materials: ["cardboard", "tambrite", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/box_with_lid_auto_bottom_c07420c2bf.svg", template: 'auto-bottom' },
  { code: 's010_v0', model: 's010', variant: 'v0', title: "Tuck end handle box", slug: 'handle-box-tuck-end', categories: ["SF"], defaultA: 120, defaultB: 80, defaultH: 110, panelCount: 15, alphaCount: 11, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/handle_box_tuck_end_855ac6cf25.svg", template: 'handle-box' },
  { code: 's010_v1', model: 's010', variant: 'v1', title: "1-2-3 bottom handle box", slug: 'handle-box-1-2-3-bottom', categories: ["123B", "SF"], defaultA: 120, defaultB: 80, defaultH: 110, panelCount: 15, alphaCount: 11, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/handle_box_1_2_3_bottom_0f105dce78.svg", template: 'handle-box' },
  { code: 's010_v2', model: 's010', variant: 'v2', title: "Auto bottom handle box", slug: 'handle-box-crash-lock-bottom', categories: ["AB", "SF"], defaultA: 120, defaultB: 80, defaultH: 110, panelCount: 17, alphaCount: 13, materials: ["cardboard", "corrugated", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/handle_box_crash_lock_bottom_6e38a86aec.svg", template: 'handle-box' },
  { code: 's011_v0', model: 's011', variant: 'v0', title: "Double wall tray", slug: 'tray-double-wall', categories: ["AC", "TL"], defaultA: 150, defaultB: 85, defaultH: 30, panelCount: 17, alphaCount: 6, materials: ["cardboard", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/tray_double_wall_22136d06f9.svg", template: 'tray-box' },
  { code: 's011_v1', model: 's011', variant: 'v1', title: "Standard tray", slug: 'tray-standard', categories: ["AC", "TL"], defaultA: 150, defaultB: 85, defaultH: 30, panelCount: 15, alphaCount: 8, materials: ["cardboard", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/tray_standard_bd870342e1.svg", template: 'tray-box' },
  { code: 's012_v0', model: 's012', variant: 'v0', title: "Standard sleeve", slug: 'sleeve-standard', categories: ["AC", "TL"], defaultA: 150, defaultB: 80, defaultH: 30, panelCount: 5, alphaCount: 1, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/sleeve_standard_822fab977d.svg", template: 'sleeve-insert' },
  { code: 's012_v2', model: 's012', variant: 'v2', title: "Slim sleeve", slug: 'sleeve-slim', categories: ["AC", "TL"], defaultA: 150, defaultB: 10, defaultH: 80, panelCount: 5, alphaCount: 1, materials: ["cardboard", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/sleeve_slim_d58117ec3d.svg", template: 'sleeve-insert' },
  { code: 's012_v3', model: 's012', variant: 'v3', title: "Flat sleeve", slug: 'sleeve-flat', categories: ["AC"], defaultA: 150, defaultB: 0, defaultH: 100, panelCount: 5, alphaCount: 1, materials: ["cardboard", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/sleeve_flat_d616dc5b4c.svg", template: 'sleeve-insert' },
  { code: 's013_v0', model: 's013', variant: 'v0', title: "1-2-3 bottom open end box", slug: 'open-end-box-1-2-3-bottom', categories: ["123B", "RF"], defaultA: 80, defaultB: 80, defaultH: 130, panelCount: 9, alphaCount: 5, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/open_end_box_1_2_3_bottom_1a5b550b1a.svg", template: 'plateau-snap' },
  { code: 's013_v1', model: 's013', variant: 'v1', title: "Auto bottom open end box", slug: 'open-end-box-crash-lock-bottom', categories: ["AB", "RF"], defaultA: 120, defaultB: 80, defaultH: 100, panelCount: 11, alphaCount: 7, materials: ["cardboard", "corrugated", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/open_end_box_crash_lock_bottom_681b94be77.svg", template: 'plateau-snap' },
  { code: 's013_v2', model: 's013', variant: 'v2', title: "Open end box with tuck end bottom", slug: 'open-end-box-tuck-end', categories: ["RF"], defaultA: 80, defaultB: 80, defaultH: 130, panelCount: 9, alphaCount: 5, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/open_end_box_tuck_end_26e6380720.svg", template: 'plateau-snap' },
  { code: 's014_v0', model: 's014', variant: 'v0', title: "1-2-3 bottom dispenser box", slug: 'dispenser-box-1-2-3-bottom', categories: ["123B", "DB", "RF", "SF"], defaultA: 90, defaultB: 90, defaultH: 160, panelCount: 15, alphaCount: 12, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/dispenser_box_1_2_3_bottom_e1d307f016.svg", template: 'dispenser-box' },
  { code: 's014_v1', model: 's014', variant: 'v1', title: "Auto bottom dispenser box", slug: 'dispenser-box-crash-lock-bottom', categories: ["AB", "DB", "RF", "SF"], defaultA: 90, defaultB: 90, defaultH: 160, panelCount: 17, alphaCount: 14, materials: ["cardboard", "corrugated", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/dispenser_box_crash_lock_bottom_450d79ea6a.svg", template: 'dispenser-box' },
  { code: 's015_v0', model: 's015', variant: 'v0', title: "1-2-3 bottom display box", slug: 'display-box-1-2-3-bottom', categories: ["123B", "DB", "SF"], defaultA: 80, defaultB: 200, defaultH: 55, panelCount: 14, alphaCount: 9, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/display_box_1_2_3_bottom_aec6edb684.svg", template: 'display-stand' },
  { code: 's015_v1', model: 's015', variant: 'v1', title: "Auto bottom display box", slug: 'display-box-crash-lock-bottom', categories: ["AB", "DB", "SF"], defaultA: 80, defaultB: 200, defaultH: 65, panelCount: 16, alphaCount: 11, materials: ["cardboard", "corrugated", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/display_box_crash_lock_bottom_931c7eaf00.svg", template: 'display-stand' },
  { code: 's016_v0', model: 's016', variant: 'v0', title: "Gable top box auto bottom", slug: 'gable-top-box-auto-bottom', categories: ["AB", "SF"], defaultA: 120, defaultB: 80, defaultH: 250, panelCount: 23, alphaCount: 18, materials: ["cardboard", "corrugated", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/gable_top_box_auto_bottom_6422859c9e.svg", template: 'gable' },
  { code: 's016_v1', model: 's016', variant: 'v1', title: "1-2-3 bottom gable top box", slug: 'gable-top-box-1-2-3-bottom', categories: ["SF"], defaultA: 160, defaultB: 80, defaultH: 250, panelCount: 21, alphaCount: 16, materials: ["cardboard", "corrugated", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/gable_top_box_1_2_3_bottom_1c6dc5be21.svg", template: 'gable' },
  { code: 's017_v1', model: 's017', variant: 'v1', title: "1-2-3 bottom gable bag box", slug: 'gable-bag-box-1-2-3-bottom', categories: ["SF", "AC"], defaultA: 160, defaultB: 50, defaultH: 250, panelCount: 12, alphaCount: 12, materials: ["cardboard", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/gable_bag_box_closed_1_2_3_bottom_6a85cc4dc6.svg", template: 'gable' },
  { code: 's017_v4', model: 's017', variant: 'v4', title: "Auto bottom bag box", slug: 'bag-box-auto-bottom', categories: ["AC", "SF"], defaultA: 120, defaultB: 50, defaultH: 250, panelCount: 11, alphaCount: 11, materials: ["cardboard", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/bag_box_open_auto_bottom_1_3495256312.svg", template: 'gable' },
  { code: 's018_v0', model: 's018', variant: 'v0', title: "Full overlap seal end box", slug: 'seal-end-box-full-overlap', categories: ["RF"], defaultA: 150, defaultB: 80, defaultH: 200, panelCount: 13, alphaCount: 13, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/seal_end_box_full_overlap_4830a83e67.svg", template: 'seal-end' },
  { code: 's019_v0', model: 's019', variant: 'v0', title: "Flat folder rounded pocket glued", slug: 'flat-folder-rounded-pocket-glued', categories: ["AC"], defaultA: 220, defaultB: 0, defaultH: 300, panelCount: 4, alphaCount: 2, materials: ["cardboard", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/flat_folder_glue_fixed_rounded_pocket_e454741362.svg", template: 'etiquette-sac-ovale' },
  { code: 's019_v1', model: 's019', variant: 'v1', title: "Flat folder with glue-fixed, diagonal pocket", slug: 'flat-folder-diagonal-pocket-glued', categories: ["AC"], defaultA: 220, defaultB: 0, defaultH: 300, panelCount: 4, alphaCount: 2, materials: ["cardboard", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/flat_folder_glue_fixed_diagonal_pocket_06dca405c2.svg", template: 'etiquette-sac-ovale' },
  { code: 's020_v0', model: 's020', variant: 'v0', title: "-", slug: '--------', categories: [], defaultA: 300, defaultB: 200, defaultH: 150, panelCount: 13, alphaCount: 0, materials: ["corrugated"], corrugated: false, mockup: "", template: 'box' },
  { code: 's020_v1', model: 's020', variant: 'v1', title: "RSC regular slotted container same length flaps", slug: 'RSC-regular-slotted-container-same-length-flaps', categories: [], defaultA: 290, defaultB: 200, defaultH: 150, panelCount: 13, alphaCount: 13, materials: ["corrugated"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/rsc_regular_slotted_container_with_same_lenght_flaps_56a297f321.svg", template: 'box' },
  { code: 's021_v0', model: 's021', variant: 'v0', title: "Telescopic dispenser box", slug: 'scatola-dispenser-telescopica', categories: ["SF"], defaultA: 80, defaultB: 80, defaultH: 150, panelCount: 22, alphaCount: 22, materials: ["cardboard"], corrugated: true, mockup: "", template: 'dispenser-box' },
  { code: 's022_v0', model: 's022', variant: 'v0', title: "Insert with customizable cutouts", slug: 'box-insert-custom-cutouts', categories: ["AC"], defaultA: 200, defaultB: 100, defaultH: 30, panelCount: 5, alphaCount: 4, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/insert_customizable_cutouts_864ddcac10.svg", template: 'calage-insert' },
  { code: 's023_v0', model: 's023', variant: 'v0', title: "Roll end tuck top box with front hooking", slug: 'roll-end-tuck-top-box', categories: ["SF"], defaultA: 180, defaultB: 110, defaultH: 40, panelCount: 15, alphaCount: 11, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/roll_end_tuck_top_box_front_hooking_white_5529954c04.svg", template: 'tuck-end' },
  { code: 's024_v0', model: 's024', variant: 'v0', title: "clamshell", slug: 'clamshell', categories: [], defaultA: 80, defaultB: 80, defaultH: 150, panelCount: 11, alphaCount: 9, materials: [], corrugated: true, mockup: "", template: 'book-box' },
  { code: 's025_v0', model: 's025', variant: 'v0', title: "Separator with central creasing", slug: 'separator-with-central-creasing', categories: ["AC"], defaultA: 150, defaultB: 60, defaultH: 20, panelCount: 4, alphaCount: 2, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/separator_with_central_creasing_ea2f04bf50.svg", template: 'separateur' },
  { code: 's026_v0', model: 's026', variant: 'v0', title: "Handle Top box", slug: 'top-box', categories: ["SF", "RF"], defaultA: 200, defaultB: 150, defaultH: 40, panelCount: 15, alphaCount: 8, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/top_box_with_handle_7412c4cb49.svg", template: 'handle-box' },
  { code: 's027_v0', model: 's027', variant: 'v0', title: "Gable top box without handle crash lock bottom", slug: 'gable-top-box-without-handle-crash-lock-bottom', categories: ["AB", "SF"], defaultA: 150, defaultB: 80, defaultH: 250, panelCount: 23, alphaCount: 16, materials: ["cardboard", "corrugated", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/gable_top_box_without_handle_crash_lock_bottom_e41ff2f237.svg", template: 'gable' },
  { code: 's029_v0', model: 's029', variant: 'v0', title: "Self assembly tray two side rollover", slug: 'self-assembly-tray-two-side-rollover', categories: [], defaultA: 160, defaultB: 120, defaultH: 40, panelCount: 9, alphaCount: 5, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/self_assembly_tray_two_side_rollover_df076d5d45.svg", template: 'ear-box' },
  { code: 's030_v0', model: 's030', variant: 'v0', title: "Envelope flat with overlapping flaps and hook", slug: 'envelope-flat-overlapping-flaps-hook', categories: ["AC"], defaultA: 100, defaultB: 100, defaultH: 0, panelCount: 5, alphaCount: 4, materials: ["cardboard", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/envelope_flat_overlapping_flaps_hook_abc309b083.svg", template: 'envelope' },
  { code: 's030_v1', model: 's030', variant: 'v1', title: "Envelope capacitive with spine and overlapping flaps", slug: 'envelope-capacitive-with-spine-and-overlapping-flaps', categories: [], defaultA: 120, defaultB: 180, defaultH: 15, panelCount: 10, alphaCount: 6, materials: ["cardboard", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/envelope_capacitive_with_spine_and_overlapping_flaps_3818b060b8.svg", template: 'envelope' },
  { code: 's031_v0', model: 's031', variant: 'v0', title: "Deluxe bellow box locking flap auto bottom", slug: 'deluxe-bellow-box-bottle-tube-neck-lock-auto-bottom', categories: [], defaultA: 80, defaultB: 80, defaultH: 230, panelCount: 20, alphaCount: 20, materials: ["cardboard", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/deluxe_bellow_box_with_locking_flap_auto_bottom_d58101ec26.svg", template: 'soufflet-ferme' },
  { code: 's032_v0', model: 's032', variant: 'v0', title: "Deluxe bellow box bottle tube neck lock 1-2-3 bottom", slug: 'deluxe-bellow-box-bottle-tube-neck-lock-1-2-3-bottom', categories: [], defaultA: 80, defaultB: 80, defaultH: 190, panelCount: 18, alphaCount: 15, materials: ["cardboard", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/deluxe_bellow_box_with_locking_flap_1_2_3_bottom_bf070f1ff2.svg", template: 'deluxe-soufflet' },
  { code: 's033_v0', model: 's033', variant: 'v0', title: "Box with bottle tube neck lock tuck to front auto bottom", slug: 'box-with-bottle-tube-neck-lock-tuck-to-front-auto-bottom', categories: [], defaultA: 85, defaultB: 85, defaultH: 225, panelCount: 18, alphaCount: 18, materials: ["cardboard", "corrugated", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/box_with_bottle_tube_neck_lock_tuck_to_font_auto_bottom_e4e8fb98ac.svg", template: 'soufflet-ferme' },
  { code: 's034_v0', model: 's034', variant: 'v0', title: "Box with bottle tube neck lock tuck to front and 1-2-3 bottom", slug: 'box-with-bottle-tube-neck-lock-tuck-to-front-1-2-3-bottom', categories: [], defaultA: 80, defaultB: 80, defaultH: 190, panelCount: 16, alphaCount: 13, materials: ["cardboard", "corrugated", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/box_with_bottle_tube_neck_lock_tuck_to_front_1_2_3_bottom_fcc787cdd4.svg", template: 'soufflet-ferme' },
  { code: 's035_v0', model: 's035', variant: 'v0', title: "mailing folder with double wall reinforcement", slug: 'mailing-folder-with-double-wall-reinforcement', categories: [], defaultA: 210, defaultB: 150, defaultH: 25, panelCount: 16, alphaCount: 10, materials: ["cardboard", "corrugated", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/mailing_folder_with_double_wall_reinforcement_597879d03f.svg", template: 'mailer' },
  { code: 's036_v0', model: 's036', variant: 'v0', title: "Mailer envelope capacitive", slug: 'mailer-envelope-capacitive', categories: ["SF"], defaultA: 150, defaultB: 20, defaultH: 210, panelCount: 5, alphaCount: 4, materials: ["cardboard", "corrugated", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/mailer_envelope_capacitive_05e5b97de5.svg", template: 'mailer' },
  { code: 's036_v1', model: 's036', variant: 'v1', title: "Mailer envelope flat", slug: 'mailer-envelope-flat', categories: ["SF"], defaultA: 150, defaultB: 0, defaultH: 210, panelCount: 5, alphaCount: 4, materials: ["cardboard", "corrugated", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/mailer_envelope_flat_7e7cf49fb9.svg", template: 'mailer' },
  { code: 's037_v0', model: 's037', variant: 'v0', title: "Pillow box", slug: 'pillow-box', categories: ["SF"], defaultA: 100, defaultB: 40, defaultH: 150, panelCount: 7, alphaCount: 7, materials: ["cardboard", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/pillow_box_with_opening_buttonhole_87ff1c2703.svg", template: 'pillow-box' },
  { code: 's038_v0', model: 's038', variant: 'v0', title: "Bag topper with rounded corners and euro hole", slug: 'bag-topper-rounded-corners-euro-hole', categories: ["RF", "SF"], defaultA: 100, defaultB: 0, defaultH: 100, panelCount: 2, alphaCount: 2, materials: ["cardboard", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/bag_toppers_rounded_corners_euro_hole_fbf4652948.svg", template: 'banderole-fine' },
  { code: 's038_v1', model: 's038', variant: 'v1', title: "Bag topper with rounded corners", slug: 'bag-topper-rounded-corners', categories: ["RF", "SF"], defaultA: 100, defaultB: 0, defaultH: 100, panelCount: 2, alphaCount: 2, materials: ["cardboard", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/bag_toppers_rounded_corners_3146330124.svg", template: 'banderole-fine' },
  { code: 's038_v2', model: 's038', variant: 'v2', title: "Bag topper with oval shape", slug: 'bag-topper-oval-shape', categories: ["RF", "SF"], defaultA: 100, defaultB: 0, defaultH: 100, panelCount: 2, alphaCount: 2, materials: ["cardboard", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/bag_toppers_oval_shape_b63deafbb8.svg", template: 'banderole-fine' },
  { code: 's038_v3', model: 's038', variant: 'v3', title: "Bag topper oval shaped with euro hole", slug: 'bag-topper-oval-shape-euro-hole', categories: ["RF", "SF"], defaultA: 100, defaultB: 0, defaultH: 100, panelCount: 2, alphaCount: 2, materials: ["cardboard", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/bag_toppers_oval_shape_euro_hole_b9d37e4d2a.svg", template: 'banderole-fine' },
  { code: 's039_v0', model: 's039', variant: 'v0', title: "Counter display without lid", slug: 'counter-display-without-lid', categories: ["DB", "SF"], defaultA: 200, defaultB: 250, defaultH: 100, panelCount: 12, alphaCount: 10, materials: ["cardboard", "corrugated", "polythene", "kraft"], corrugated: true, mockup: "https://strapi.pack.ly/uploads/counter_display_381d3a78d8.svg", template: 'display-stand' },
]
