import type { Template } from './types'

export const TEMPLATES: Template[] = [
  { id: 'box', name: 'Box', description: 'Standard RSC box' },
  { id: 'mailer', name: 'Mailer Box', description: 'Self-locking mailer' },
  { id: 'tuck-end', name: 'Tuck-End Box', description: 'Tuck-end closure' },
  { id: 'display', name: 'Display Box', description: 'Open-top display' },
  { id: 'flip-top', name: 'Flip-Top Box', description: 'Hinged flip top' },
  { id: 'gable', name: 'Gable Box', description: 'Milk carton style' },
  { id: 'seal-end', name: 'Seal End Box', description: 'Sealed end closure' },
  { id: 'snap-lock', name: 'Snap-Lock Tray', description: 'Snap-lock base tray' },
  { id: 'auto-bottom', name: 'Auto-Bottom Box', description: 'Auto-lock bottom' },
  { id: 'lid-box', name: 'Lid Box', description: '2-piece gift box with lid' },
  { id: 'pillow-box', name: 'Pillow Box', description: 'Curved pillow/bow packaging' },
  { id: 'drawer-box', name: 'Drawer Box', description: 'Slide-out drawer sleeve' },
  { id: 'hexagonal-box', name: 'Boîte Hexagonale', description: 'Prisme hexagonal 6 faces' },
  { id: 'cylinder-box', name: 'Boîte Cylindrique', description: 'Tube cylindrique avec couvercle' },
  { id: 'tray-box', name: 'Tray Box', description: 'Plateau 4 angles verrouillés' },
  { id: 'reverse-tuck', name: 'Reverse Tuck', description: 'Tuck inversé haut/bas' },
  { id: 'book-box', name: 'Book Box', description: 'Boîte clamshell style livre' },
  { id: 'stand-up-pouch', name: 'Stand-Up Pouch', description: 'Sachet souple avec soufflet' },
  { id: 'crash-lock-bottom', name: 'Crash Lock Bottom', description: 'Fond auto-verrou à clipsage' },
  { id: 'window-box', name: 'Window Box', description: 'Boîte avec fenêtre arrondie' },
  { id: 'sleeve-insert', name: 'Sleeve + Insert', description: 'Étui manchon + plateau intérieur' },
  { id: 'shrink-sleeve', name: 'Shrink Sleeve', description: 'Manchon thermorétractable 360°' },
  { id: 'iml-label', name: 'IML Label', description: 'Étiquette In-Mold Labeling' },
  { id: 'flow-wrap', name: 'Flow Wrap', description: 'Film étirable alimentaire' },
  { id: 'blister-pack', name: 'Blister Pack', description: 'Blister clamshell médical/pharma' },
  { id: 'ballotin', name: 'Ballotin', description: 'Boîte chocolaterie avec couvercle' },
  { id: 'fourreau-rigide', name: 'Fourreau Rigide', description: 'Étui glissant rigide luxe' },
  { id: 'thermoform-tray', name: 'Plateau Thermoformé', description: 'Insert thermoformé coffret' },
  { id: 'envelope', name: 'Enveloppe', description: 'Enveloppe standard avec rabat' },
  { id: 'shallow-box', name: 'Boîte Plate', description: 'Plateau peu profond type coffret' },
  { id: 'ear-box', name: 'Coffret Oreilles', description: 'Boîte FEFCO 0426 sans colle, oreilles latérales' },
  { id: 'soufflet-partiel', name: 'Soufflet Partiel', description: 'Boîte soufflet latéral expansible' },
  { id: 'soufflet-ferme', name: 'Soufflet Fermé', description: 'Boîte soufflet intégralement scellée' },
  { id: 'banderole', name: 'Banderole', description: 'Manchon wrap-around ouvert aux deux bouts' },
  { id: 'banderole-fine', name: 'Banderole Fine', description: 'Banderole étroite type belly-band' },
  { id: 'handle-box', name: 'Boîte Poignée', description: 'Boîte fond auto + découpe poignée arche' },
  { id: 'hanging-box', name: 'Boîte Accrochage', description: 'Tuck-end + euro-slot découpe accrochage' },
  { id: 'dispenser-box', name: 'Boîte Distributrice', description: 'Boîte présentoir avec fente distributrice' },
  { id: 'display-stand', name: 'Présentoir', description: 'Boîte inclinée pour présentation en rayon' },
  { id: 'berlingot', name: 'Berlingot', description: 'Carton gable-top style boîte lait/jus' },
  { id: 'fourreau-auto', name: 'Fourreau Auto', description: 'Fourreau fond automatique sans colle' },
  { id: 'fourreau-semi-auto', name: 'Fourreau Semi-Auto', description: 'Fourreau fond semi-automatique 1 colle' },
  { id: 'calage-insert', name: 'Calage Insert', description: 'Insert alvéolé accordéon pour cloisons internes' },
  { id: 'separateur', name: 'Séparateur', description: 'Cloison centrale simple pliée' },
  { id: 'etiquette-sac-ovale', name: 'Étiquette Sac Ovale', description: 'Étiquette ferme-sac ovale avec encoche' },
  { id: 'plateau-snap', name: 'Plateau Sans Colle', description: 'Plateau à clips interlocking sans adhésif' },
  { id: 'deluxe-soufflet', name: 'Deluxe Soufflet', description: 'Boîte premium RSC + panneaux soufflet latéraux' },
]
