'use client'

import { useMemo, useEffect, useRef } from 'react'
import { useFrame, useThree } from '@react-three/fiber'
import * as THREE from 'three'
import { printingVertexShader, printingFragmentShader } from '../../lib/shaders/printingShader'

export interface PrintingMaterialProps {
  boardColor?: string              // substrate hex color
  cmyk?: [number, number, number, number]
  laminate?: 0 | 1 | 2            // none / matte / gloss
  varnishMask?: THREE.Texture | null
  varnishAmt?: number
  albedoTex?: THREE.Texture | null
  imageMix?: number                // 0=KM only, 1=image only
  side?: THREE.Side
  uvOffset?: [number, number]      // UV origin shift for inter-panel continuity
  uvScale?: [number, number]       // UV scale for inter-panel continuity
  alphaTex?: THREE.Texture | null  // panel shape alpha mask (generated by alphaShapes.ts)
}

function makeWhiteTex(): THREE.DataTexture {
  const t = new THREE.DataTexture(new Uint8Array([255, 255, 255, 255]), 1, 1, THREE.RGBAFormat)
  t.needsUpdate = true
  return t
}

export function usePrintingMaterial({
  boardColor = '#ffffff',
  cmyk = [0, 0, 0, 0],
  laminate = 0,
  varnishMask = null,
  varnishAmt = 0,
  albedoTex = null,
  imageMix = 0.5,
  side = THREE.FrontSide,
  uvOffset = [0, 0],
  uvScale = [1, 1],
  alphaTex = null,
}: PrintingMaterialProps): THREE.ShaderMaterial {
  const { camera } = useThree()

  const c = new THREE.Color(boardColor)

  // Stable 1×1 white texture used as fallback when a sampler must be bound but has no real data.
  const wt = useRef<THREE.DataTexture | null>(null)
  if (!wt.current) wt.current = makeWhiteTex()

  const mat = useMemo(() => {
    const white = makeWhiteTex()
    return new THREE.ShaderMaterial({
      vertexShader:   printingVertexShader,
      fragmentShader: printingFragmentShader,
      side,
      transparent: false,
      alphaTest:   0,
      uniforms: {
        uBoardColor:  { value: new THREE.Vector3(c.r, c.g, c.b) },
        uCMYK:        { value: new THREE.Vector4(...cmyk) },
        uLaminate:    { value: laminate },
        uVarnishMask: { value: white },
        uVarnishAmt:  { value: varnishAmt },
        uAlbedoTex:   { value: white },
        uImageMix:    { value: imageMix },
        uHasImage:    { value: false },
        uCameraPos:   { value: new THREE.Vector3() },
        uUvOffset:    { value: new THREE.Vector2(...uvOffset) },
        uUvScale:     { value: new THREE.Vector2(...uvScale) },
        uAlphaTex:    { value: white },
        uHasAlpha:    { value: false },
      },
    })
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [side])

  // Sync uniforms reactively without rebuilding the material
  useEffect(() => {
    const white = wt.current!
    const col = new THREE.Color(boardColor)
    mat.uniforms.uBoardColor.value.set(col.r, col.g, col.b)
    mat.uniforms.uCMYK.value.set(...cmyk)
    mat.uniforms.uLaminate.value    = laminate
    mat.uniforms.uVarnishMask.value = varnishMask ?? white
    mat.uniforms.uVarnishAmt.value  = varnishAmt
    mat.uniforms.uImageMix.value    = imageMix
    mat.uniforms.uHasImage.value    = albedoTex !== null
    mat.uniforms.uUvOffset.value.set(uvOffset[0], uvOffset[1])
    mat.uniforms.uUvScale.value.set(uvScale[0], uvScale[1])

    // Ensure artwork enters Beer-Lambert in linear space
    if (albedoTex) albedoTex.colorSpace = THREE.SRGBColorSpace
    mat.uniforms.uAlbedoTex.value = albedoTex ?? white

    mat.uniforms.uAlphaTex.value = alphaTex ?? white
    mat.uniforms.uHasAlpha.value = alphaTex !== null
    mat.transparent = alphaTex !== null
    mat.alphaTest   = alphaTex !== null ? 0.5 : 0
    mat.needsUpdate = true
  }, [mat, boardColor, cmyk, laminate, varnishMask, varnishAmt, albedoTex, imageMix, uvOffset, uvScale, alphaTex])

  useFrame(() => {
    mat.uniforms.uCameraPos.value.copy(camera.position)
  })

  useEffect(() => () => mat.dispose(), [mat])

  return mat
}
